# -*- coding: utf-8 -*-
"""aprendendo_matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JyIMdexzEygnIwEoK6za4MEPiUiE8Uph
"""

# importação do pacote
import matplotlib.pyplot as plt

x = [1,2,3,4]
y = [2,3,4,3]

plt.plot(x,y)
plt.show()

# algumas edições possíveis (sempre consultar documentação)
plt.plot(x,y, label = 'dados')
plt.ylabel('Eixo y')
plt.xlabel('Eixo x')
plt.title('Título do gráfico')
plt.xticks([2,4,6,8,9])
plt.yticks([-1,3,5,9,11])
plt.legend()
plt.show()

# propriedade da linha (sempre consultar na documentação outros tipos de linestyle, color e largura na linha  (lw))
plt.plot(x,y, linestyle = ':', color='g', lw=10.0)
plt.show()

# grafico de pontos
plt.scatter(x,y, color='k')
plt.show()

# gráfico de barra
plt.bar(x,y, color='g')
plt.show()

# mudar o tipo de marcador do gráfico
plt.scatter(x,y, color='k', marker='v')
plt.show()

# alterando os limitres dos gráficos
plt.plot(x,y)
plt.axis('square')
plt.show()

# gerar mais de uma figura
valoresx = [1, 2, 3, 4]
valoresy = [1, 4, 2, 3]

figura = plt.figure(figsize=(20,3))
figura.suptitle('Título Geral')

figura.add_subplot(131)
plt.plot(valoresx, valoresy, label='Um dado qualquer')
plt.legend()
plt.title('Gráfico 1')

figura.add_subplot(133)
plt.scatter(valoresx, valoresy)
plt.title('Gráfico 2')

figura.add_subplot(132)
plt.bar(valoresx, valoresy)
plt.title('Gráfico 3')

#plt.savefig('grafico.png')

plt.show(figura)

# aplicação: fonte de dados kaggle

import pandas as pd

cotacao_df = pd.read_csv('/content/indexData.csv')
display(cotacao_df)

cotacao_df1 = cotacao_df[['Index', 'Date', 'Close']]
display(cotacao_df1)

dfremove = cotacao_df1.loc[(cotacao_df1['Index']!='NYA')]
cotacao_dffinal = cotacao_df1.drop(dfremove.index)
cotacao_dffinal = cotacao_dffinal[13900:]
display(cotacao_dffinal)

plt.figure(figsize=(20,4))
plt.plot(cotacao_dffinal['Date'], cotacao_dffinal['Close'], label='NYA', color='r', ls='--', lw='2')
plt.title('Cotação histórica da bolsa NYA')
plt.ylabel('Cotação')
plt.xlabel('Data')
plt.legend()
plt.xticks(['2021-03-23', '2021-04-23', '2021-05-03'])

plt.show()